import pandas as pd
csv = pd.read_csv("PYTHON-FULL\Machine Learning\PANDAS\customers-100.csv")
# print(csv)
# print(csv.loc[[0,5]])
# print(csv.head())
# print(csv.head(9))
# print(csv.tail())
# print(csv.tail(9))
# print(csv.shape)
# print(csv.size)
# print(csv.ndim)
# print(csv.info())
# print(csv.dtypes)
# print(csv.describe())
# print(csv['City'].describe())
# print(type(csv["City"]))
# print(csv["City"])
print(csv.iloc[:,0])
# print(type(csv.iloc[:,0]))